// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCv7OM3zpnbQa0kCSW-TWjukcWdrBb4NJk',
    appId: '1:482413508589:web:28e63a59d459caf9dc19e4',
    messagingSenderId: '482413508589',
    projectId: 'education-app-1ec2f',
    authDomain: 'education-app-1ec2f.firebaseapp.com',
    storageBucket: 'education-app-1ec2f.firebasestorage.app',
    measurementId: 'G-X5HKCRG712',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZqg3SmqoHNrphZigcbZNvYJ7g6Zp7MAk',
    appId: '1:482413508589:android:d0efc02a51ecfa48dc19e4',
    messagingSenderId: '482413508589',
    projectId: 'education-app-1ec2f',
    storageBucket: 'education-app-1ec2f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9Es4QPEsO4N-hxz362_9NZXb7o7TckWg',
    appId: '1:482413508589:ios:7dce7bd9e42fb8cadc19e4',
    messagingSenderId: '482413508589',
    projectId: 'education-app-1ec2f',
    storageBucket: 'education-app-1ec2f.firebasestorage.app',
    iosBundleId: 'com.example.educationApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9Es4QPEsO4N-hxz362_9NZXb7o7TckWg',
    appId: '1:482413508589:ios:7dce7bd9e42fb8cadc19e4',
    messagingSenderId: '482413508589',
    projectId: 'education-app-1ec2f',
    storageBucket: 'education-app-1ec2f.firebasestorage.app',
    iosBundleId: 'com.example.educationApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCv7OM3zpnbQa0kCSW-TWjukcWdrBb4NJk',
    appId: '1:482413508589:web:3ce6ba9bb7a00179dc19e4',
    messagingSenderId: '482413508589',
    projectId: 'education-app-1ec2f',
    authDomain: 'education-app-1ec2f.firebaseapp.com',
    storageBucket: 'education-app-1ec2f.firebasestorage.app',
    measurementId: 'G-6JE9BW93WB',
  );
}
